"""empty message

Revision ID: dfcd06ec40e8
Revises: 093f4c909c77
Create Date: 2022-08-05 15:14:57.078649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfcd06ec40e8'
down_revision = '093f4c909c77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venue', 'no_upcoming_shows')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('no_upcoming_shows', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
